"""empty message

Revision ID: 2990cd4d7b4c
Revises: 153ede58bf4e
Create Date: 2023-07-30 09:46:23.738068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2990cd4d7b4c'
down_revision = '153ede58bf4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=50), nullable=False))
        batch_op.alter_column('product_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.alter_column('product_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('title')

    # ### end Alembic commands ###
