"""empty message

Revision ID: 6d146288179d
Revises: 7b41b7b2c3f4
Create Date: 2023-07-18 18:53:37.100486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '6d146288179d'
down_revision = '7b41b7b2c3f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProductType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('auth_token', sa.String(length=300), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('portfolio_url', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('registered', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['type'], ['UserType.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('Product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('logo', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('promo_images', postgresql.ARRAY(sqlalchemy_utils.types.url.URLType()), nullable=True),
    sa.Column('web_site', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('client', sa.Integer(), nullable=False),
    sa.Column('registered', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client'], ['Client.id'], ),
    sa.ForeignKeyConstraint(['type'], ['UserType.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('FavouriteProducts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client', sa.Integer(), nullable=False),
    sa.Column('product', sa.Integer(), nullable=False),
    sa.Column('registered', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client'], ['Client.id'], ),
    sa.ForeignKeyConstraint(['product'], ['Product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('client')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('photo', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('auth_token', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('portfolio_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('registered', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='client_pkey'),
    sa.UniqueConstraint('password', name='client_password_key'),
    sa.UniqueConstraint('phone', name='client_phone_key')
    )
    op.drop_table('FavouriteProducts')
    op.drop_table('Product')
    op.drop_table('Client')
    op.drop_table('UserType')
    op.drop_table('ProductType')
    # ### end Alembic commands ###
