"""empty message

Revision ID: 7b41b7b2c3f4
Revises: b7942fed2b92
Create Date: 2023-07-13 22:22:37.155203

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '7b41b7b2c3f4'
down_revision = 'b7942fed2b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('photo', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('auth_token', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('portfolio_url', sqlalchemy_utils.types.url.URLType(), nullable=True))
        batch_op.add_column(sa.Column('registered', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['password'])
        batch_op.create_unique_constraint(None, ['phone'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('registered')
        batch_op.drop_column('portfolio_url')
        batch_op.drop_column('type')
        batch_op.drop_column('auth_token')
        batch_op.drop_column('password')
        batch_op.drop_column('description')
        batch_op.drop_column('photo')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
